name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]"
labels: ["enhancement"]
projects:
  - "2024-2025-Project-4-Team-5 Quality Assurance Planning"
type: Feature
body:
  - type: input
    id: description
    attributes:
      label: Description
      description: Describe the feature you are proposing.
      placeholder: A clear and concise description of the feature you are proposing.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation And Context
      description: Explain why this feature is needed and how it will benefit users.
      placeholder: |
        Explain why this feature is needed and how it will benefit users.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your solution or the desired behavior.
      placeholder: |
        Describe your solution or the desired behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or features you considered.
      placeholder: |
        List any alternative solutions or features you considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false